version: "3"

services:
    jupyterhub:
        container_name: jupyterhub-docker
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - type: bind
              read_only: true
              source: /var/run/docker.sock
              target: /var/run/docker.sock
        ports:
            - "8000:8000"
        networks:
            - default

networks:
    default:
        name: jupyterhub-network
