version: "3"

services:
    jupyterhub:
        container_name: lti-jupyterhub-docker
        build:
            dockerfile: Dockerfile
            context: .
        volumes:
            - type: bind
              read_only: true
              source: /var/run/docker.sock
              target: /var/run/docker.sock
        ports:
            - "8000:8000"
        networks:
            - jupyterhub
    
    moodle-php:
        container_name: docker-moodle-php
        build:
          dockerfile: moodle/Dockerfile
        ports:
          - "80:80"
        networks:
            - moodle
            - jupyterhub
        profiles:
            - with-moodle
  
    mariadb:
        container_name: docker-moodle-mariadb
        image: mariadb:latest
        environment:
            MARIADB_USER: moodle
            MARIADB_PASSWORD: moodle
            MARIADB_ROOT_PASSWORD: moodle      
        networks:
            - moodle
        profiles:
            - with-moodle

networks:
    jupyterhub:
        name: jupyterhub-network
    moodle:
        name: moodle-network
